### PR TITLE
chore(deps): bump imagemagick to 7.1.1-24

### PR DESCRIPTION
**Pull request by mertalev**
### Description

This release contains a fix for RW2 images that should fix [this](https://github.com/immich-app/immich/issues/3494) issue.

### CODE REVIEW

**Comment by martabal** [comment]
You have to change the patch. Can you change the incorrect LIBVIPS_REVISION in the libraw install too ?

Another question, why did you switch from curl/wget to git ?

**Comment by bo0tzz** [comment]
The switch to git is from #26

**Comment by mertalev** [comment]
> You have to change the patch. Can you change the incorrect LIBVIPS_REVISION in the libraw install too ?
> 
> Another question, why did you switch from curl/wget to git ?

Good catch on the libraw script!

**Review by alextran1502 — APPROVED** [review]

**Comment by alextran1502** [comment]
@mertalev Let's merge it and test before we push out a new release

**Comment by mertalev** [comment]
Sounds good

**Comment by t3dc** [comment]
On 1.103.1, but still just getting trash for my RW2 images.

Is there some package I need to update? On an RPi5 running Immich in docker.

Screenshot 2024-05-08 at 10 00 07 AM

**Comment by mertalev** [comment]
Could you provide a sample image? Also, how new is your camera model? It could be too new for our version of libraw.

**Comment by t3dc** [comment]
It's an S5 IIx, so fairly new. Here's a [download link](https://cloud.coxbros.us/index.php/s/3CTMxEDaSDgyfLn) for a sample image.

**Comment by t3dc** [comment]
> You can re-run thumbnail generation on these assets once the issue is fixed.

Excellent. Thanks! 

> It should be supported in our libraw in that case. Hmm, I'll look into this. Could you make an issue for easier tracking?

Yep. Happy to set up an issue.

**Pull request merged**
