### PR TITLE
Update libjxl-dev and libjxl to 0.9, fix jxl export by Adobe ACR decode failed

### PR DESCRIPTION
**Pull request by nidbCN**
Releated issue: [Failed to generate preview for Adobe ACR exported JXL picture. · Issue #11938 · immich-app/immich](https://github.com/immich-app/immich/issues/11938)

The depencies `libjxl-dev` and `libjxl0.7` are a little old and may cause some JXL decode failed(such as Adobe ACR export one). This pull request upgrade them to 0.9 (channel: debian testing) .

I had manually build and test several JXL files.

## images build

All images (dev and prod) build success without error.

## JXL test

There're four JXL files, half of them are Adobe ACR exported and others are transcode using libjxl offical tools.

In each two files, one is lossless, 16bit deepth and another is lessly, 8bit deepth.

Here are the file list:

image

Upload those files and they works fine.

image
image

This is my first pull request, if there's and problem, please comment and I'll try fix.

### CODE REVIEW

**Review by mertalev — APPROVED** [review]
Thank you for the PR!

**Comment by martabal** [comment]
Why not `libjxl0.10` ?

**Comment by nidbCN** [comment]
> Why not `libjxl0.10` ?
> 
> Edit: Ah my bad, only available in experimental

yeap, only 0.7 and 0.9 abailable in current sources

**Comment by martabal** [comment]
If we really want the latest version, we can use the .deb they release on github https://github.com/libjxl/libjxl/releases

**Comment by nidbCN** [comment]
> If we really want the latest version, we can use the .deb they release on github https://github.com/libjxl/libjxl/releases

So should I change it to latest version? 

But the github release only provides package for amd64 and x86, if the base-image should support others arch, we need to build the libjxl.

**Comment by martabal** [comment]
> But the github release only provides package for amd64 and x86

Dang it

Then, yes using the package from the testing repo is the best solution. Unless there's issues which are only solved in the latest version (0.10.x), I don't think it makes sense to build it from source.

**Review by martabal — APPROVED** [review]

**Comment by mertalev** [comment]
Ready to merge after the merge conflict is resolved.

**Pull request merged**
