### PR TITLE
feat: keep build lock

### PR DESCRIPTION
**Pull request by martabal**
Keep `build-lock.json` for the About page

### CODE REVIEW

**Review by bo0tzz — APPROVED** [review]

**Comment by martabal** [comment]
> Sweet, while we're here any thoughts about keeping /var/apt/lists/ as well?

I think it's a good practice to remove this directory

**Comment by bo0tzz** [comment]
@martabal @jrasm91 do we still need this or has it staled?

**Comment by jrasm91** [comment]
Looks like we can merge this. The only change is not deleting the build-lock.json file, which is fine IMO. The files are copied to the container twice so that's why one of them is removed in this PR.

**Comment by martabal** [comment]
Not needed, but it's good to have it if we want to build something with it

**Pull request merged**
